In [1]:
import torch

In [2]:
x = torch.ones(5)

In [3]:
y = torch.zeros(3)

In [5]:
w = torch.randn(5, 3, requires_grad = True)

In [6]:
b = torch.randn(3, requires_grad = True)

In [7]:
z = torch.matmul(x, w) + b

In [8]:
z

tensor([ 4.9520,  2.4354, -1.1352], grad_fn=<AddBackward0>)

In [9]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(
    z,
    y)

In [10]:
print(f"Gradient function for z = {z.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x000001C03CB2C3A0>


In [11]:
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000001C03CB2C3A0>


In [12]:
loss.backward()

In [13]:
print(w.grad)

tensor([[0.3310, 0.3065, 0.0811],
        [0.3310, 0.3065, 0.0811],
        [0.3310, 0.3065, 0.0811],
        [0.3310, 0.3065, 0.0811],
        [0.3310, 0.3065, 0.0811]])


In [14]:
print(b.grad)

tensor([0.3310, 0.3065, 0.0811])


##### END