In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
device

'cuda'

In [12]:
class NeuralNetwork(
    nn.Module,
    ):
    
    def __init__(
        self
        ):
        super(
            NeuralNetwork, 
            self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512, 10)
            )
        
    def forward(
        self,
        x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [13]:
model = NeuralNetwork().to(device)

In [14]:
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [15]:
X = torch.rand(1, 28, 28, device = device)

In [17]:
logits = model(X)

In [19]:
pred_probab = nn.Softmax(dim = 1)(logits)

In [20]:
pred_probab

tensor([[0.0975, 0.1010, 0.0993, 0.1009, 0.0918, 0.1046, 0.0972, 0.1077, 0.1014,
         0.0986]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [23]:
y_pred = pred_probab.argmax(1)

In [24]:
print(f"Predicted class: {y_pred}")

Predicted class: tensor([7], device='cuda:0')


In [28]:
input_image = torch.rand(3,28,28)

In [29]:
input_image.size()

torch.Size([3, 28, 28])

In [27]:
flatten = nn.Flatten()

In [30]:
flat_image = flatten(input_image)

In [31]:
flat_image.size()

torch.Size([3, 784])

In [32]:
layer1 = nn.Linear(
    in_features = 28*28,
    out_features = 20
    )

In [34]:
hidden1 = layer1(flat_image)

In [35]:
hidden1.size()

torch.Size([3, 20])

In [36]:
hidden1

tensor([[ 0.2857, -0.1499, -0.3709, -0.1989, -0.4130,  0.1529,  0.2882,  0.0182,
          0.1174,  0.1636, -0.5226, -0.5106, -0.1532, -0.1804,  0.1797, -0.3608,
         -0.4066, -0.1069,  0.0069, -0.2376],
        [ 0.3028, -0.4913, -0.0369,  0.0108, -0.0285,  0.0046,  0.4348,  0.4380,
          0.1489, -0.0225, -0.1729, -0.6569, -0.3202,  0.1359,  0.0804, -0.4459,
         -0.4656, -0.0598, -0.3958, -0.1191],
        [ 0.1137, -0.1186,  0.2247,  0.0129, -0.2934,  0.0902,  0.5779,  0.2643,
          0.1694,  0.0784, -0.4520, -0.0782, -0.2752, -0.2661,  0.3103, -0.4763,
         -0.5173,  0.2965, -0.2175, -0.2492]], grad_fn=<AddmmBackward0>)

In [37]:
hidden1 = nn.ReLU()(hidden1)

In [38]:
hidden1

tensor([[0.2857, 0.0000, 0.0000, 0.0000, 0.0000, 0.1529, 0.2882, 0.0182, 0.1174,
         0.1636, 0.0000, 0.0000, 0.0000, 0.0000, 0.1797, 0.0000, 0.0000, 0.0000,
         0.0069, 0.0000],
        [0.3028, 0.0000, 0.0000, 0.0108, 0.0000, 0.0046, 0.4348, 0.4380, 0.1489,
         0.0000, 0.0000, 0.0000, 0.0000, 0.1359, 0.0804, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.1137, 0.0000, 0.2247, 0.0129, 0.0000, 0.0902, 0.5779, 0.2643, 0.1694,
         0.0784, 0.0000, 0.0000, 0.0000, 0.0000, 0.3103, 0.0000, 0.0000, 0.2965,
         0.0000, 0.0000]], grad_fn=<ReluBackward0>)

##### END