In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
device

'cuda'

In [12]:
class NeuralNetwork(
    nn.Module,
    ):
    
    def __init__(
        self
        ):
        super(
            NeuralNetwork, 
            self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512, 10)
            )
        
    def forward(
        self,
        x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [13]:
model = NeuralNetwork().to(device)

In [14]:
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [15]:
X = torch.rand(1, 28, 28, device = device)

In [17]:
logits = model(X)

In [19]:
pred_probab = nn.Softmax(dim = 1)(logits)

In [20]:
pred_probab

tensor([[0.0975, 0.1010, 0.0993, 0.1009, 0.0918, 0.1046, 0.0972, 0.1077, 0.1014,
         0.0986]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [23]:
y_pred = pred_probab.argmax(1)

In [24]:
print(f"Predicted class: {y_pred}")

Predicted class: tensor([7], device='cuda:0')


In [28]:
input_image = torch.rand(3,28,28)

In [29]:
input_image.size()

torch.Size([3, 28, 28])

In [27]:
flatten = nn.Flatten()

In [30]:
flat_image = flatten(input_image)

In [31]:
flat_image.size()

torch.Size([3, 784])

In [32]:
layer1 = nn.Linear(
    in_features = 28*28,
    out_features = 20
    )

In [34]:
hidden1 = layer1(flat_image)

In [35]:
hidden1.size()

torch.Size([3, 20])

In [36]:
hidden1

tensor([[ 0.2857, -0.1499, -0.3709, -0.1989, -0.4130,  0.1529,  0.2882,  0.0182,
          0.1174,  0.1636, -0.5226, -0.5106, -0.1532, -0.1804,  0.1797, -0.3608,
         -0.4066, -0.1069,  0.0069, -0.2376],
        [ 0.3028, -0.4913, -0.0369,  0.0108, -0.0285,  0.0046,  0.4348,  0.4380,
          0.1489, -0.0225, -0.1729, -0.6569, -0.3202,  0.1359,  0.0804, -0.4459,
         -0.4656, -0.0598, -0.3958, -0.1191],
        [ 0.1137, -0.1186,  0.2247,  0.0129, -0.2934,  0.0902,  0.5779,  0.2643,
          0.1694,  0.0784, -0.4520, -0.0782, -0.2752, -0.2661,  0.3103, -0.4763,
         -0.5173,  0.2965, -0.2175, -0.2492]], grad_fn=<AddmmBackward0>)

In [37]:
hidden1 = nn.ReLU()(hidden1)

In [38]:
hidden1

tensor([[0.2857, 0.0000, 0.0000, 0.0000, 0.0000, 0.1529, 0.2882, 0.0182, 0.1174,
         0.1636, 0.0000, 0.0000, 0.0000, 0.0000, 0.1797, 0.0000, 0.0000, 0.0000,
         0.0069, 0.0000],
        [0.3028, 0.0000, 0.0000, 0.0108, 0.0000, 0.0046, 0.4348, 0.4380, 0.1489,
         0.0000, 0.0000, 0.0000, 0.0000, 0.1359, 0.0804, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.1137, 0.0000, 0.2247, 0.0129, 0.0000, 0.0902, 0.5779, 0.2643, 0.1694,
         0.0784, 0.0000, 0.0000, 0.0000, 0.0000, 0.3103, 0.0000, 0.0000, 0.2965,
         0.0000, 0.0000]], grad_fn=<ReluBackward0>)

In [39]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
    )

In [40]:
input_image = torch.rand(3, 28,28)

In [45]:
logits = seq_modules(
    input_image)

In [42]:
logits

tensor([[ 0.1163, -0.2119, -0.0744,  0.0219,  0.2341, -0.3438, -0.3983,  0.4193,
         -0.0112, -0.1047],
        [-0.1168, -0.0100,  0.0731,  0.0283,  0.1995, -0.1358, -0.2967,  0.3080,
          0.0305, -0.1462],
        [-0.0330, -0.1033,  0.0247,  0.0452,  0.1594, -0.2422, -0.2953,  0.3030,
         -0.1229, -0.1653]], grad_fn=<AddmmBackward0>)

In [43]:
softmax = nn.Softmax(dim =1)

In [46]:
pred_probab = softmax(logits)

In [47]:
pred_probab

tensor([[0.1130, 0.0814, 0.0934, 0.1029, 0.1272, 0.0714, 0.0676, 0.1530, 0.0995,
         0.0906],
        [0.0883, 0.0982, 0.1068, 0.1021, 0.1211, 0.0866, 0.0738, 0.1350, 0.1023,
         0.0857],
        [0.0995, 0.0927, 0.1054, 0.1075, 0.1206, 0.0807, 0.0765, 0.1392, 0.0909,
         0.0871]], grad_fn=<SoftmaxBackward0>)

In [49]:
pred_probab.sum(1)

tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)

In [50]:
model

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [51]:
for name, param, in model.named_parameters():
    print(f"Layer:{name} | Size: {param.size()} | Values: {param[:2]} \n")

Layer:linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values: tensor([[ 0.0081, -0.0022, -0.0318,  ..., -0.0351,  0.0033,  0.0257],
        [ 0.0233,  0.0273,  0.0045,  ..., -0.0331, -0.0206, -0.0136]],
       device='cuda:0', grad_fn=<SliceBackward0>) 

Layer:linear_relu_stack.0.bias | Size: torch.Size([512]) | Values: tensor([ 0.0092, -0.0229], device='cuda:0', grad_fn=<SliceBackward0>) 

Layer:linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values: tensor([[-0.0249,  0.0344,  0.0242,  ..., -0.0160,  0.0340,  0.0131],
        [ 0.0184, -0.0328, -0.0141,  ...,  0.0332,  0.0111, -0.0339]],
       device='cuda:0', grad_fn=<SliceBackward0>) 

Layer:linear_relu_stack.2.bias | Size: torch.Size([512]) | Values: tensor([-0.0327,  0.0167], device='cuda:0', grad_fn=<SliceBackward0>) 

Layer:linear_relu_stack.4.weight | Size: torch.Size([10, 512]) | Values: tensor([[ 0.0333,  0.0100,  0.0057,  ...,  0.0273,  0.0269,  0.0211],
        [ 0.0212, -0.0259, -0.0013,  ..., -0.

##### END