In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]

In [3]:
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)

In [6]:
x_np = torch.from_numpy(np_array)

In [7]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [8]:
x_ones = torch.ones_like(x_data)

In [9]:
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [10]:
x_rand = torch.rand_like(x_data, dtype = torch.float)

In [11]:
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.2344, 0.5545],
        [0.0778, 0.7743]]) 



In [12]:
shape = (2,3,)

In [13]:
rand_tensor = torch.rand(shape)

print(f"Random Tensor: \n {rand_tensor} \n")

Random Tensor: 
 tensor([[0.3179, 0.7584, 0.1946],
        [0.7050, 0.6231, 0.5265]]) 



In [14]:
ones_tensor = torch.ones(shape)

print(f"Ones Tensor: \n {ones_tensor} \n")

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [15]:
zeros_tensor = torch.zeros(shape)

print(f"Zeros Tensor: \n {zeros_tensor}")

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [16]:
tensor = torch.rand(3,4)

In [17]:
tensor.shape

torch.Size([3, 4])

In [18]:
tensor.dtype

torch.float32

In [22]:
tensor.device

device(type='cuda', index=0)

In [21]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [27]:
tensor = torch.rand(4,4)

In [28]:
tensor

tensor([[0.0740, 0.1967, 0.2905, 0.5790],
        [0.2559, 0.1339, 0.3339, 0.8658],
        [0.2812, 0.0735, 0.7953, 0.5948],
        [0.4468, 0.6632, 0.0963, 0.3371]])

In [24]:
tensor[0]

tensor([1., 1., 1., 1.])

In [30]:
tensor[:,0]

tensor([0.0740, 0.2559, 0.2812, 0.4468])

In [29]:
tensor[...,-1]

tensor([0.5790, 0.8658, 0.5948, 0.3371])

In [31]:
tensor[:,1] = 0.0

In [32]:
tensor

tensor([[0.0740, 0.0000, 0.2905, 0.5790],
        [0.2559, 0.0000, 0.3339, 0.8658],
        [0.2812, 0.0000, 0.7953, 0.5948],
        [0.4468, 0.0000, 0.0963, 0.3371]])

In [33]:
t1 = torch.cat([
    tensor,
    tensor,
    tensor,
], dim = 1)

In [34]:
t1

tensor([[0.0740, 0.0000, 0.2905, 0.5790, 0.0740, 0.0000, 0.2905, 0.5790, 0.0740,
         0.0000, 0.2905, 0.5790],
        [0.2559, 0.0000, 0.3339, 0.8658, 0.2559, 0.0000, 0.3339, 0.8658, 0.2559,
         0.0000, 0.3339, 0.8658],
        [0.2812, 0.0000, 0.7953, 0.5948, 0.2812, 0.0000, 0.7953, 0.5948, 0.2812,
         0.0000, 0.7953, 0.5948],
        [0.4468, 0.0000, 0.0963, 0.3371, 0.4468, 0.0000, 0.0963, 0.3371, 0.4468,
         0.0000, 0.0963, 0.3371]])

In [39]:
tensor = torch.ones(3,2)

In [40]:
tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [41]:
y1 = tensor @tensor.T

In [42]:
y1

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [43]:
tensor.matmul(tensor.T)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [44]:
y3 = torch.rand_like(y1)

In [45]:
y3

tensor([[0.8373, 0.0832, 0.4877],
        [0.6208, 0.7410, 0.4784],
        [0.5000, 0.5184, 0.2759]])

In [46]:
torch.matmul(tensor, tensor.T, out = y3)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [47]:
y3

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [48]:
tensor * tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [49]:
tensor.mul(tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [50]:
z3 = torch.rand_like(tensor)

In [51]:
torch.mul(tensor, tensor, out = z3)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [52]:
z3

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [55]:
type(tensor.sum().item())

float

In [56]:
tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [58]:
tensor.add_(5)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]])

In [59]:
tensor.copy_(z3)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [60]:
t = torch.ones(5)

In [61]:
t

tensor([1., 1., 1., 1., 1.])

In [62]:
n = t.numpy()

In [63]:
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [64]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [65]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

In [66]:
n = np.ones(5)

In [67]:
t = torch.from_numpy(n)

In [69]:
np.add(n, 1, out = n)

array([2., 2., 2., 2., 2.])

In [70]:
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

##### END