In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]

In [3]:
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)

In [6]:
x_np = torch.from_numpy(np_array)

In [7]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [8]:
x_ones = torch.ones_like(x_data)

In [9]:
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [10]:
x_rand = torch.rand_like(x_data, dtype = torch.float)

In [11]:
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.2344, 0.5545],
        [0.0778, 0.7743]]) 



In [12]:
shape = (2,3,)

In [13]:
rand_tensor = torch.rand(shape)

print(f"Random Tensor: \n {rand_tensor} \n")

Random Tensor: 
 tensor([[0.3179, 0.7584, 0.1946],
        [0.7050, 0.6231, 0.5265]]) 



In [14]:
ones_tensor = torch.ones(shape)

print(f"Ones Tensor: \n {ones_tensor} \n")

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [15]:
zeros_tensor = torch.zeros(shape)

print(f"Zeros Tensor: \n {zeros_tensor}")

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [16]:
tensor = torch.rand(3,4)

In [17]:
tensor.shape

torch.Size([3, 4])

In [18]:
tensor.dtype

torch.float32

In [22]:
tensor.device

device(type='cuda', index=0)

In [21]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

##### END